#!/usr/bin/env python
import sys, os, re, time
from subprocess import call

if len(sys.argv) is 1:
  print "Usage: autorun <file>"
  exit()
else:
  file = sys.argv[1]

try:
  while True:
    currenttime = time.time()
    filetime = os.stat(file).st_mtime

    if filetime > currenttime-1:
      print "Preparing to run: %s" % file
      
      # os.system("php -f %s" % file)
      return_code = call("php -f %s" % file, shell=True)
      if return_code is 0:
        print "Executed Successfully"
      elif return_code is 1:
        print "Execution Failed"
      else:
        print "Received a response of: %d" % return_code

      print "\nExecution Completed"
      print "Took %s seconds\n\n" % (time.time() - currenttime)
    time.sleep(1)
except KeyboardInterrupt:
  exit()
